model_list:
  - model_name: "claude-opus-4-6"
    litellm_params:
      model: "claude-proxy/opus"

  - model_name: "claude-opus-4-6-high"
    litellm_params:
      model: "claude-proxy/opus:high"

  - model_name: "claude-opus-4-6-max"
    litellm_params:
      model: "claude-proxy/opus:max"

  - model_name: "claude-sonnet-4-6"
    litellm_params:
      model: "claude-proxy/sonnet"

  - model_name: "claude-sonnet-4-6-high"
    litellm_params:
      model: "claude-proxy/sonnet:high"

  - model_name: "claude-sonnet-4-6-max"
    litellm_params:
      model: "claude-proxy/sonnet:max"

  - model_name: "claude-haiku-4-5"
    litellm_params:
      model: "claude-proxy/haiku"

  - model_name: "claude-haiku-4-5-high"
    litellm_params:
      model: "claude-proxy/haiku:high"

  - model_name: "claude-haiku-4-5-max"
    litellm_params:
      model: "claude-proxy/haiku:max"

litellm_settings:
  custom_provider_map:
    - provider: "claude-proxy"
      custom_handler: handler.handler
